### ISSUE TITLE
How to solve CUDA out of memory ?

### ISSUE THREAD

**Issue by Michaelwhite34** [LizhenWangT/FaceVerse#16]
I am using gtx 1660ti with 6gb vram.

**Comment by Michaelwhite34** [comment]
Processing: 45576d11ffe4dd13222ffdd.jpeg
Speed:20.1300,    1 /    2, 0.1049
  0%|                                                   | 0/800 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "fit_images.py", line 414, in <module>
    fit(args, device)
  File "fit_images.py", line 252, in fit
    rendered_img = faceverse_model.renderer.alb_renderer(mesh)
  File "/home/michael/anaconda3/envs/quick_test_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/michael/anaconda3/envs/quick_test_env/lib/python3.8/site-packages/pytorch3d/renderer/mesh/renderer.py", line 62, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/home/michael/anaconda3/envs/quick_test_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/michael/anaconda3/envs/quick_test_env/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shader.py", line 262, in forward
    colors = flat_shading(
  File "/home/michael/anaconda3/envs/quick_test_env/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 219, in flat_shading
    ambient, diffuse, specular = _apply_lighting(
  File "/home/michael/anaconda3/envs/quick_test_env/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 33, in _apply_lighting
    light_specular = lights.specular(
  File "/home/michael/anaconda3/envs/quick_test_env/lib/python3.8/site-packages/pytorch3d/renderer/lighting.py", line 280, in specular
    return specular(
  File "/home/michael/anaconda3/envs/quick_test_env/lib/python3.8/site-packages/pytorch3d/renderer/lighting.py", line 152, in specular
    reflect_direction = -direction + 2 * (cos_angle[..., None] * normals)
RuntimeError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 5.80 GiB total capacity; 3.86 GiB already allocated; 52.88 MiB free; 3.90 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Michaelwhite34** [comment]
Processing: 45576d11ffe4dd13222ffdd.jpeg
Speed:5.5962,    1 /    2, 18.7387
  0%|                                                   | 0/800 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "fit_images.py", line 414, in <module>
    fit(args, device)
  File "fit_images.py", line 234, in fit
    detail_img, _ = g_detail([latent_detail], input_detail * mask_detail, return_latents=True, noise=noises_detail)
  File "/home/michael/anaconda3/envs/quick_test_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/michael/Downloads/FaceVerse-main/network.py", line 648, in forward
    out = conv1(out, latent[:, i], noise=noise1)
  File "/home/michael/anaconda3/envs/quick_test_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/michael/Downloads/FaceVerse-main/network.py", line 360, in forward
    out = self.conv(input, style)
  File "/home/michael/anaconda3/envs/quick_test_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/michael/Downloads/FaceVerse-main/network.py", line 258, in forward
    weight = self.scale * self.weight * style
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 5.80 GiB total capacity; 2.06 GiB already allocated; 57.94 MiB free; 2.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Michaelwhite34** [comment]
Someone please help -- Really struggling to get this working

**Comment by LizhenWangT** [comment]
Maybe you can try to comment out all the code related to the expression network. (Line 291 # fitting with the exp ckpt & the model loading started from Line 76)

**Comment by Michaelwhite34** [comment]
> Maybe you can try to comment out all the code related to the expression network. (Line 291 # fitting with the exp ckpt & the model loading started from Line 76)
 
Should I just delete fit_images line 291 to line 341 or just comment out these lines with exp ?
